[build]
  base = "CERtoUSER_Suite_Starter_Plus_FixModules"
  command = "npm run build"
  publish = "site"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "handlebars", "pizzip", "docxtemplater", "nanoid", "busboy"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
