[build]
  # Publish from the repo root so Netlify doesn't duplicate the base path
  publish = "."
  # Functions folder relative to the repo root
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  SAFE_MODE = "false"

[context.deploy-preview.environment]
  SAFE_MODE = "true"

[context.branch-deploy.environment]
  # keep branch deploys read-only while reviewing changes
  SAFE_MODE = "true"
