[build]
  base = "CERtoUSER_Suite_Starter_Plus_FixModules"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  SAFE_MODE = "false"

[context.deploy-preview.environment]
  SAFE_MODE = "true"

[context.branch-deploy.environment]
  SAFE_MODE = "true"
