[build]
  command = "npm ci || npm i"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg","handlebars","pizzip","docxtemplater","nanoid","busboy"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  DEV_NO_AUTH = "true"
